// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TDD.Data;

#nullable disable

namespace TDD.Migrations
{
    [DbContext(typeof(BuDbContext))]
    partial class BuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("TDD.Data.Adherent", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Civilite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Adherent");
                });

            modelBuilder.Entity("TDD.Data.Livre", b =>
                {
                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT")
                        .HasColumnName("isbn");

                    b.Property<string>("AdherentCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Editeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Isbn");

                    b.HasIndex("AdherentCode");

                    b.ToTable("Livres");
                });

            modelBuilder.Entity("TDD.Data.MigrationHistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MigrationId");

                    b.ToTable("__EFMigrationsHistory");
                });

            modelBuilder.Entity("TDD.Data.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AdherentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT")
                        .HasColumnName("dateDebut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("dateFin");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("isbn");

                    b.Property<string>("LivreIsbn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdherentCode");

                    b.HasIndex("LivreIsbn");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TDD.Data.Livre", b =>
                {
                    b.HasOne("TDD.Data.Adherent", null)
                        .WithMany("LivresReserves")
                        .HasForeignKey("AdherentCode");
                });

            modelBuilder.Entity("TDD.Data.Reservation", b =>
                {
                    b.HasOne("TDD.Data.Adherent", "Adherent")
                        .WithMany()
                        .HasForeignKey("AdherentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDD.Data.Livre", "Livre")
                        .WithMany()
                        .HasForeignKey("LivreIsbn");

                    b.Navigation("Adherent");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("TDD.Data.Adherent", b =>
                {
                    b.Navigation("LivresReserves");
                });
#pragma warning restore 612, 618
        }
    }
}
